### ISSUE TITLE
cannot sign in on iOS 16+

### ISSUE THREAD

**Issue by wasgehthierab** [Rov3r/scmusicplus#1]
Hey there, 

thanks for the effort. I am not able to sign in on iOS 16. I try to follow your guide, but when I uninstall the signed in app store app and open your application afterwards it is signed out and I am not able to sign in again.

Is there a way to make it work in iOS 16 as well?

thx

**Comment by Rov3r** [comment]
Thanks for your feedback.

Yes, unfortunately this is a problem only on iOS 16. It also has nothing to do with SCMusicPlus, but rather SoundCloud itself. The app can detect when it is sideloaded (which is why iOS 15 Trollstore users have no issues). When the app has detected that it is not the App Store application, it will reject all sign in credentials even when they are valid.

I have not been able to work around this issue yet from within the tweak, but thanks to a couple of users, we were able to confirm that Google Accounts can still sign in. Personally I don't like linking Google or Facebook to my other accounts so I do not recommend this workaround to those who are willing to wait for an actual bypass (no telling when it is coming, I will admit it might take a while since I'm new to this). You could also create a dummy account and use it only for this application.

_To sign in on iOS 16, you have a couple choices (personal preference):_
- Pair your Google Account with your existing SoundCloud account
- Use your Google Account with a new SoundCloud account
- Pair your Facebook Account with your existing SoundCloud account
- Use your Facebook Account with a new SoundCloud account

From here, sign into the app store app and continue the sideloading steps like normal.


**If you skip Google Account sign in to the app store app and try to login directly on the SCMusicPlus ipa, you will have to use the same mitigation as the sideloaded YouTube users. The instructions to this can be found here: https://github.com/qnblackcat/uYouPlus/discussions/447. I will look into solving this issue very soon so that you all can at least sign in on the modded ipa directly.

_If for some reason anything explained above does not work, let me know._

**Comment by wasgehthierab** [comment]
I tried to login with Google and it works. Thank you for that workaround. 
I agree with you, that without google it would be better. But thank you, this way I can use the application already until you got it also working in another way :)

**Comment by Isaacsworlddd** [comment]
I just came across from this by a friend on discord and he sent me this because I was trying to find a SC++ IPA that works for IOS 16 for my friends and while reading this it looks like you have done amazing work! : ) I just wanted to ask you if you can just confirm that this IPA that you have developed also has full premium advantages as other SC++
