### ISSUE TITLE
Not available for non-jailbreak???

### ISSUE THREAD

**Issue by KaaaooS** [Rov3r/scmusicplus#10]
Idk so much,but i see .deb its only for jailbreak,and supossed its not more available for non-jailbreak

**Comment by Rov3r** [comment]
Yes, I no longer provide the ipa due to possible copyright infringement. For non-jailbroken devices, you must use a desktop application like Sideloadly to combine the deb with the iOS app.

You can check out this post on Reddit to get more information about alternative methods to get decrypted App Store apps: https://reddit.com/r/sideloaded/comments/u20ejv/release_online_decrypted_ios_ipa_store_easily/
